name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Hello
        run: echo "Hello"
