name: Build and Deploy
on:
  - push
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.HOST }}
          POSTGRES_HOSTNAME: ${{ secrets.NAME }}
        ports:
          - 5432:5432
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: instalando o python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: instalar dependencias
        run: pip install -r requirements.txt
      - name: Esperando o PostgreSQL ficar pronto
        run: sleep 15
      - name: Executar pytest
        env:
          DATABASE_URL: postgresql://${{ secrets.USER }}:${{ secrets.PASSWORD }}@${{ secrets.HOST }}:5432/${{ secrets.NAME }}
        run: pytest teste.py
